-- MySQL Script generated by MySQL Workbench
-- Do 14 Jan 2021 11:25:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`lernende`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lernende` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vorname` VARCHAR(255) NOT NULL,
  `nachname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ortschaften`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ortschaften` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plz` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`markers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`markers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lon` DOUBLE NOT NULL,
  `lat` DOUBLE NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `ort_id` INT NOT NULL,
  `lernende_ids` TEXT(1000) NULL DEFAULT '[]',
  PRIMARY KEY (`id`),
  INDEX `ort_id_idx` (`ort_id` ASC) VISIBLE,
  CONSTRAINT `ort_id`
    FOREIGN KEY (`ort_id`)
    REFERENCES `mydb`.`ortschaften` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lernende_ids`
    FOREIGN KEY ()
    REFERENCES `mydb`.`lernende` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
