version: "3.6"

services: 
  app:
    image: php:8
    volumes: 
      - ./src:/var/www/html
    command: "php -S 0.0.0.0:8000 -t /var/www/html"
    ports: 
      - "8000:8000"
  
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: happy-place

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
